/* Chapter7 Ex07 Prime numbers can also be generated by an algorithm known as the Sieve of Eratosthenes. The algorithm for this procedure is presented here. Write a program that implements this algorithm. Have the program find all prime numbers up to n = 150. What can you say about this algorithm as compared to the ones used in the text for calculating prime numbers?

Sieve of Eratosthenes Algorithm
To Display All Prime Numbers Between 1 and n
Step 1:     Define an array of integers P. Set all elements Pi to 0, 2 <= i <= n.
Step 2:     Set i to 2.
Step 3:     If i > n, the algorithm terminates.
Step 4:     If Pi is 0, then i is prime.
Step 5:     For all positive integer values of j, such that i x j ≤ n,  set Pixj to 1.
Step 6:     Add 1 to i and go to step 3. */

#include <stdio.h>

int main(void)
{
    int P[151] = {0}; /* Step 1:     Define an array of integers P. Set all elements Pi to 0, 2 <= i <= n. */
    int i, j;

    /* Only need to use i up to sqrt(150) ≈ 12 */
    for (i = 2; i * i <= 150; ++i) /* Step 2:     Set i to 2. */
    {
        if (P[i] == 0) /* Step 4:     If Pi is 0, then i is prime. */
        {
            for (j = i * 2; j <= 150; j += i) /* Step 6:     Add 1 to i and go to step 3. */
            {
                P[j] = 1; /* Step 5:     For all positive integer values of j, such that i x j ≤ n,  set Pixj to 1. */
            }
        }
    }

    for (i = 2; i <= 150; ++i) /* Step 3:     If i > n, the algorithm terminates. */
    {
        if (P[i] == 0)
            printf("%d ", i);
    }
    printf("\n");

    return 0;
}

/* OUTCOME */
// 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149

/* Comment */
// The exercise refers to Eratorthenes Algorithm without using it exactly the process of finding the prime numders exactly!
// It is mistaked to have multiple iterations, instead check till the square root of the n, which is 150. So, the 150^2 is 12.25

// If the above logic will be eliminated, then it is not Greek Eratorthenes Algorithm. As a concequence it causes more iterancies within for loops, which are uneccessery. 
