/* Chapter5 Ex03 A triangular number can also be generated by the formula triangular = n ( n + 1) / 2 for any integer value of n. For example, the 10th triangular number, 55, can be generated by substituting 10 as the value for n in the preceding formula. Write a program that generates a table for triangular numbers using the preceding formula. Have the program generate every fifth triangular number between 5 and 50 (that is 5, 10, 15, ..., 50). */

#include <stdio.h>

int main(void) 
{
    int n, triangular;

    // Print column headings
    printf("%4s%15s\n", "n", "Triangular(n)");
    printf("-------------------------\n");

    // Loop from 5 to 50, incrementing by 5
    for (n = 5; n <= 50; n += 5) 
    {
        triangular = n * (n + 1) / 2;
        printf("%4d%15d\n", n, triangular);
    }

    return 0;
}

/* OUTCOME */
//   n  Triangular(n)
// -------------------------
//   5              15
//   10             55
//   15            120
//   20            210
//   25            325
//   30            465
//   35            630
//   40            820
//   45           1035
//   50           1275


/* The %4s or %15s it is an output, so it prints a number with right-aligned in a 4/15-character field. */

